# Generated by Django 4.1 on 2024-07-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appUsers", "0002_ingredient_recipe_review_recipeingredient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealplan",
            name="recipes",
        ),
        migrations.RemoveField(
            model_name="mealplan",
            name="user",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="ingredient",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="review",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
        migrations.DeleteModel(
            name="MealPlan",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
        migrations.DeleteModel(
            name="RecipeIngredient",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
